version: '3.8'

services:
  analyst-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DOCKER_ENABLED=true
      - CACHE_DIR=/app/cache
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
      - analyst_cache:/app/cache
      - analyst_uploads:/app/uploads
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - analyst-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - analyst-network

  # Optional: MongoDB for advanced caching/logging
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - analyst-network

volumes:
  analyst_cache:
  analyst_uploads:
  redis_data:
  mongodb_data:

networks:
  analyst-network:
    driver: bridge
